language: python
python:
  - 3.6
script:
  - python app.py freeze
deploy:
  provider: script
  skip_cleanup: true
  script: python app.py deploy --no-freeze --no-push
  on:
    branch: master
    repo: jackmoody11/jackmoody11.github.io
env:
  global:
    secure: 2iXnUjGK9l2Mwh1IaLAlQxtqopNMq4pVdLqetLAfC5Bi3umPtTTYs5WSx8AF5wwKhPC+pIE53VnG0xb44TjaKzpK4ebOcfAxEKDH17zdbbWkXbnCJF2YGb4rWTjfBPW59zHeLnD2LE+ufjUAHfskhwjGPAqvzIRPnEShMW+ajfj8F+SBSWnAl6NuxG19NvofFohGNoQOgXzzITdk217FiV8oqfiDjbLUmdFyAXYXs/vriP5RNYIPypDRwPXB32qtzixCUofocmwaJf3HlH4CPs9H77p8nz1MHDR3qiK8X2plTsj2kA9ox5NIWlGhsJoU5OCFpKo8NiAxucg3go/qoC9tBsh+EU/I1swp//wKXlRw1Rn2v1C9VNSzFGV6lmeM1kFHPwxKS/Jl+5FzTqVLxjGRw1GQx3rRwpaDD8W8XTY16jXRmbSZJRAHF1adMIA26PNR/zooJiprvdsO/f2BRUjceve+8BROM8W9aEB9WCH9+ZKL6WlB9mwhPGneY10fetyEXqk6YQRaUg1mTn/vXN73JqXVxcg5IhbTjKTXY6M7vca6xlIwVXhfoByTVKljyvutKOKFPgrCggi/HGB1wG+hHIGOfp+N6NJAMB34CVq88Iy3aMNUBtRoIfUSXPfqXEdwl8ST8Sq1fWIFwrmyseAzLwblgsAPLpITAMfZGqI=
