name: Deploy

on:
  push:
    branches: [gatsby]
  pull_request:
    branches: [gatsby]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: git config user.email "jacklaytonmoody@gmail.com"
    - run: git config user.name "Jack Moody"
    - run: npm run deploy