name: Deploy

on:
  push:
    branches: [gatsby]
  pull_request:
    branches: [gatsby]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - run: git config --global user.name "jackmoody11" && git config --global user.email "jackmoody@unc.edu"
    - run: npm install && npm run deploy