name: Test

on:
  push:
    branches: [gatsby, develop]
  pull_request:
    branches: [gatsby, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
